version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fastify-multipart
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.4
  - dependency-name: fastify
    versions:
    - 3.14.2
  - dependency-name: fastify-static
    versions:
    - 4.0.0
  registries:
  - npm-registry-registry-npmjs-org
